# bacon.toml
default_job = "run-wasm"

[jobs.run-wasm]
command = ["cargo", "watch", "-cx", "run --target wasm32-unknown-unknown"]
need_stdout = true
# optional: disable watching only default file sets
default_watch = false
# set watch dirs/file patterns
watch = ["src", "assets", "Cargo.toml"]
# optional: ignore target directory if you want
ignore = ["target", "wasm32-unknown-unknown"]
